"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "./auth-provider";
import { useDemo } from "./demo-provider";
import { Icon } from "./ui";
import { roleHome } from "@/services/demo-auth";

export function LoginPage() {
  const auth=useAuth();const demo=useDemo();const router=useRouter();
  const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [visible,setVisible]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(auth.ready&&auth.session)router.replace(roleHome(auth.session.role));},[auth.ready,auth.session,router]);
  function submit(e:FormEvent){e.preventDefault();const session=auth.login(username,password);if(!session){setError("Username atau password tidak sesuai. Gunakan akun simulasi yang tersedia.");return;}setError("");if(session.workerId){demo.setWorkerId(session.workerId);demo.setPeriod("2026-09");}router.replace(roleHome(session.role));}
  return <main className="login-shell"><section className="login-story"><div className="login-brand"><Icon/><span>SIPEKA</span></div><div className="login-story-content"><span className="login-eyebrow">Perlindungan kesehatan pekerja</span><h1>Data sesuai.<br/>Perlindungan terjaga.</h1><p>Pantau kepesertaan JKN, laporkan perbedaan, dan ikuti penanganannya dalam satu tempat.</p><div className="login-features"><div><span><Icon name="shield"/></span><div><strong>Pantau kepesertaan</strong><p>Informasi bulanan yang mudah dipahami.</p></div></div><div><span><Icon name="ticket"/></span><div><strong>Aduan yang terarah</strong><p>Klarifikasi dan tindak lanjut yang tercatat.</p></div></div><div><span><Icon name="history"/></span><div><strong>Ikuti perkembangannya</strong><p>Ketahui status dan langkah berikutnya.</p></div></div></div></div><small>Prototipe Healthkathon · Seluruh data fiktif</small></section><section className="login-panel"><div className="login-form-wrap"><div className="login-mobile-brand"><Icon/><strong>SIPEKA</strong></div><div className="eyebrow">Selamat datang</div><h2>Masuk ke SIPEKA</h2><p className="muted login-intro">Gunakan akun Anda untuk mengakses layanan sesuai peran.</p><form onSubmit={submit}><div className="field"><label htmlFor="login-username">Username</label><input id="login-username" name="username" autoComplete="username" autoCapitalize="none" spellCheck={false} required value={username} onChange={e=>{setUsername(e.target.value);setError("");}} placeholder="Masukkan username"/></div><div className="field"><label htmlFor="login-password">Password</label><div className="password-input"><input id="login-password" name="password" type={visible?"text":"password"} autoComplete="current-password" required value={password} onChange={e=>{setPassword(e.target.value);setError("");}} placeholder="Masukkan password"/><button type="button" aria-label={visible?"Sembunyikan password":"Tampilkan password"} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?"Sembunyikan":"Lihat"}</button></div></div>{error&&<p className="login-error" role="alert">{error}</p>}<button className="btn login-submit" disabled={!auth.ready}>Masuk <Icon name="arrow"/></button></form><details className="login-demo-accounts"><summary>Lihat akun simulasi</summary><div><p>Pilih akun sesuai alur yang ingin dicoba.</p><table><thead><tr><th>Username</th><th>Password</th></tr></thead><tbody><tr><td>pekerja</td><td>Pekerja123!</td></tr><tr><td>perusahaan</td><td>Perusahaan123!</td></tr><tr><td>petugas</td><td>Petugas123!</td></tr></tbody></table></div></details><p className="login-footnote"><Icon name="info"/>Login dan data menggunakan simulasi statis.</p></div><footer>SIPEKA · Sistem Informasi Perlindungan Kepesertaan Pekerja</footer></section></main>;
}
