"use client";
import Link from "next/link";
import { useState } from "react";
import { useDemo } from "./demo-provider";
import { Badge, Notice } from "./ui";
import { PageHead, basePath } from "./workspace";
import { TicketTable } from "./ticket-views";
import { checkLabels, checkTone, periodLabel,rupiah,dateLabel } from "@/domain/labels";
import type { Role } from "@/domain/schemas";

export function OrganizationHome({role}:{role:Role}){const d=useDemo();const data=d.data!;const companyId=data.workers.find(w=>w.id===d.workerId)!.companyId;const tickets=data.tickets.filter(t=>role!=="company"||t.companyId===companyId);const checks=data.checks.filter(c=>c.period===d.period&&(role!=="company"||c.companyId===companyId));const stats=role==="company"?[["Pekerja terdaftar",data.workers.filter(w=>w.companyId===companyId).length],["Perlu dicek",checks.filter(c=>c.status==="NEEDS_REVIEW").length],["Menunggu klarifikasi",tickets.filter(t=>t.status==="AWAITING_COMPANY").length],["Data belum tersedia",checks.filter(c=>c.status==="DATA_UNAVAILABLE").length]]:[["Tiket aktif",tickets.filter(t=>t.status!=="RESOLVED").length],["Laporan baru",tickets.filter(t=>t.status==="SUBMITTED").length],["Menunggu informasi",tickets.filter(t=>t.status.startsWith("AWAITING")).length],["Tiket selesai",tickets.filter(t=>t.status==="RESOLVED").length]];return <><PageHead title={role==="company"?"Ringkasan perusahaan":"Ringkasan penanganan"} description={role==="company"?"Pantau kesesuaian data dan tanggapi klarifikasi pekerja.":"Kelola laporan pekerja dan tindak lanjut pemeriksaan."}/><div className="stats">{stats.map(([label,count])=><section className="card stat" key={label}><div className="stat-title">{label}</div><strong>{count}</strong><small className="muted">Data simulasi</small></section>)}</div><Notice title={role==="company"?"Klarifikasi membantu pencocokan data":"Setiap perbedaan perlu ditinjau"}>{role==="company"?"Buka tiket yang menunggu klarifikasi, periksa periode yang sama, lalu beri penjelasan dan bukti pendukung.":"Periksa kelengkapan bukti dan catatan. Status bulanan berubah setelah data minimum tersedia dan cocok."}</Notice><section className="card"><div className="card-header"><h2>Tiket terbaru</h2><Link className="link-button" href={`${basePath(role)}${role==="bpjs"?"antrean/":"tiket/"}`}>Lihat semua tiket</Link></div><TicketTable tickets={tickets.slice(0,5)} role={role}/></section></>;}
export function OrganizationData({view}:{view:"workers"|"contributions"}){const d=useDemo();const [search,setSearch]=useState("");const data=d.data!;const companyId=data.workers.find(w=>w.id===d.workerId)!.companyId;const workers=data.workers.filter(w=>w.companyId===companyId&&w.name.toLowerCase().includes(search.toLowerCase()));return <><PageHead title={view==="workers"?"Data pekerja":"Data iuran"} description="Catatan perusahaan fiktif untuk pencocokan per periode."/><section className="card"><div className="card-header"><h2>{workers.length} pekerja</h2><input className="filter-input" aria-label="Cari pekerja" placeholder="Cari pekerja…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Pekerja</th><th>{view==="workers"?"Mulai bekerja":"Periode"}</th><th>Upah tetap</th><th>Potongan JKN</th><th>Hasil pencocokan</th></tr></thead><tbody>{workers.map(w=>{const c=data.checks.find(c=>c.workerId===w.id&&c.companyId===companyId&&c.period===d.period);return <tr key={w.id}><td><strong>{w.name}</strong><small>{w.id}</small></td><td>{view==="workers"?dateLabel(w.employmentStartDate):periodLabel(d.period)}</td><td>{rupiah(c?.declaredWage??null)}</td><td>{rupiah(c?.workerDeduction??null)}</td><td><Badge tone={checkTone(c?.status??"DATA_UNAVAILABLE")}>{checkLabels[c?.status??"DATA_UNAVAILABLE"]}</Badge></td></tr>;})}</tbody></table></div>{!workers.length&&<p className="empty">Tidak ada pekerja yang cocok dengan pencarian.</p>}</section><Notice>Data perusahaan pada prototipe ini dibaca dari placeholder JSON. Perubahan data sumber nantinya dilakukan melalui backend Anda.</Notice></>;}
export function Reports(){const d=useDemo();const tickets=d.data!.tickets;const groups=Object.entries(tickets.reduce<Record<string,number>>((acc,t)=>{acc[t.period]=(acc[t.period]??0)+1;return acc;},{}));function download(){const csv=["period,total_tickets,resolved_tickets",...groups.map(([p,n])=>`${p},${n},${tickets.filter(t=>t.period===p&&t.status==="RESOLVED").length}`)].join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="sipeka-laporan-simulasi.csv";a.click();URL.revokeObjectURL(url);}return <><PageHead title="Laporan penanganan" description="Ringkasan tiket berdasarkan periode laporan." period={false}/><section className="card"><div className="card-header"><h2>Rekap periode</h2><button className="btn secondary" onClick={download}>Unduh CSV simulasi</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Periode</th><th>Total tiket</th><th>Aktif</th><th>Selesai</th></tr></thead><tbody>{groups.map(([p,n])=><tr key={p}><td>{periodLabel(p)}</td><td>{n}</td><td>{tickets.filter(t=>t.period===p&&t.status!=="RESOLVED").length}</td><td>{tickets.filter(t=>t.period===p&&t.status==="RESOLVED").length}</td></tr>)}</tbody></table></div></section></>;}
